evm-network-id: 100
price-multiplier: 1
issue-creator-multiplier: 1
time-labels:
  - name: "Time: <1 Hour"
  - name: "Time: <2 Hours"
  - name: "Time: <4 Hours"
  - name: "Time: <1 Day"
  - name: "Time: <1 Week"
priority-labels:
  - name: "Priority: 1 (Normal)"
  - name: "Priority: 2 (Medium)"
  - name: "Priority: 3 (High)"
  - name: "Priority: 4 (Urgent)"
  - name: "Priority: 5 (Emergency)"
default-labels:
  - "Time: <1 Hour"
  - "Priority: 1 (Normal)"
payment-permit-max-price: 1000
comment-incentives: true
max-concurrent-assigns: 5
promotion-comment: ""
assistive-pricing: true
register-wallet-with-verification: false
command-settings:
  - name: start
    enabled: true
  - name: stop
    enabled: true
  - name: wallet
    enabled: true
  - name: multiplier
    enabled: true
  - name: query
    enabled: true
  - name: autopay
    enabled: true
  - name: allow
    enabled: true
  - name: help
    enabled: true
  - name: payout
    enabled: true
disable-analytics: false
enable-access-control:
  label: true
  organization: true
incentives:
  comment:
    elements:
      code: 5
      img: 5
      h1: 1
      li: 0.5
      a: 0.5
      blockquote: 0
    totals:
      word: 0.1
